### ISSUE TITLE
Issue with angular-addtocalendar and Angular 1.5/webpack

### ISSUE THREAD

**Issue by erikapierr** [jshor/angular-addtocalendar#12]
Hello,

We've installed the package via NPM but it's not working as expected. When the module is imported, we get the following error in the console: 

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module {} due to:
Error: [ng:areq] Argument 'module' is not a function, got Object
http://errors.angularjs.org/1.5.3/ng/areq?p0=module&p1=not%20a%20function%2C%20got%20Object
    at http://localhost:8080/app.js:16803:13
    at assertArg (http://localhost:8080/app.js:18579:12)
    at assertArgFn (http://localhost:8080/app.js:18589:4)
    at http://localhost:8080/app.js:21268:12
    at forEach (http://localhost:8080/app.js:17056:21)
    at loadModules (http://localhost:8080/app.js:21243:6)
    at http://localhost:8080/app.js:21260:41
    at forEach (http://localhost:8080/app.js:17056:21)
    at loadModules (http://localhost:8080/app.js:21243:6)
    at createInjector (http://localhost:8080/app.js:21165:20)
    at doBootstrap (http://localhost:8080/app.js:18445:21)
    at bootstrap (http://localhost:8080/app.js:18466:13)
    at angularInit (http://localhost:8080/app.js:18351:6)
    at http://localhost:8080/app.js:47444:6
    at HTMLDocument.trigger (http://localhost:8080/app.js:19862:8)
    at defaultHandlerWrapper (http://localhost:8080/app.js:20152:12)
http://errors.angularjs.org/1.5.3/$injector/modulerr?p0=%7B%7D&p1=Error%3A%…faultHandlerWrapper%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.js%3A20152%3A12)
    at http://localhost:8080/app.js:16803:13
    at http://localhost:8080/app.js:21282:16
    at forEach (http://localhost:8080/app.js:17056:21)
    at loadModules (http://localhost:8080/app.js:21243:6)
    at http://localhost:8080/app.js:21260:41
    at forEach (http://localhost:8080/app.js:17056:21)
    at loadModules (http://localhost:8080/app.js:21243:6)
    at createInjector (http://localhost:8080/app.js:21165:20)
    at doBootstrap (http://localhost:8080/app.js:18445:21)
    at bootstrap (http://localhost:8080/app.js:18466:13)
    at angularInit (http://localhost:8080/app.js:18351:6)
    at http://localhost:8080/app.js:47444:6
    at HTMLDocument.trigger (http://localhost:8080/app.js:19862:8)
    at defaultHandlerWrapper (http://localhost:8080/app.js:20152:12)
    at HTMLDocument.eventHandler (http://localhost:8080/app.js:20140:10)
http://errors.angularjs.org/1.5.3/$injector/modulerr?p0=app&p1=Error%3A%20%…cument.eventHandler%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.js%3A20140%3A10)
```

**Comment by jshor** [comment]
Hey - I just tried it with an ES6/Angular/Webpack build and didn't run into any issues. Did you import the module using require?

```
require('angular-addtocalendar');
```
If using ES6:
```
import 'angular-addtocalendar';
```

Otherwise there doesn't seem to be an issue with webpack. But I will clarify the imports in the README.
